SELECT * FROM AIRPORTS LIMIT 15 OFFSET 0;

SELECT * FROM AIRPORTS_DISTANCE_MATRIX WHERE ICAO_FROM = 'LDZA';

SELECT DISTINCT ICAO_FROM, ICAO_TO, DIST_TOT FROM AIRPORTS_DISTANCE_MATRIX WHERE ICAO_FROM = 'LDZA';

SELECT DISTINCT ICAO_FROM, ICAO_TO, DIST_TOT FROM AIRPORTS_DISTANCE_MATRIX WHERE ICAO_FROM = 'LDZA' LIMIT 15 OFFSET 0;

SELECT adm.ICAO_FROM, adm.ICAO_TO, adm.COUNTRY, adm.DIST_CTRY, adm.DIST_TOT  
FROM AIRPORTS a 
INNER JOIN AIRPORTS_DISTANCE_MATRIX adm ON adm.ICAO_TO = a.ICAO 
WHERE a.ISO_COUNTRY = 'HR' AND adm.ICAO_FROM = 'LDZA'

WITH airport_country AS(
	SELECT ISO_COUNTRY, ICAO
	FROM AIRPORTS
	WHERE ICAO = 'LDZA'
)
SELECT adm.ICAO_FROM, adm.ICAO_TO, adm.COUNTRY, adm.DIST_CTRY, adm.DIST_TOT  
FROM AIRPORTS a 
INNER JOIN airport_country ON airport_country.ISO_COUNTRY = a.ISO_COUNTRY 
INNER JOIN AIRPORTS_DISTANCE_MATRIX adm ON adm.ICAO_TO = a.ICAO 
WHERE adm.ICAO_FROM = airport_country.ICAO

WITH airport_country AS(
	SELECT ISO_COUNTRY, ICAO
	FROM AIRPORTS
	WHERE ICAO = 'LDZA'
)
SELECT adm.ICAO_FROM, adm.ICAO_TO, adm.COUNTRY, adm.DIST_CTRY, adm.DIST_TOT  
FROM AIRPORTS a 
INNER JOIN airport_country ON airport_country.ISO_COUNTRY = a.ISO_COUNTRY 
INNER JOIN AIRPORTS_DISTANCE_MATRIX adm ON adm.ICAO_TO = a.ICAO 
WHERE adm.ICAO_FROM = airport_country.ICAO AND adm.COUNTRY = airport_country.ISO_COUNTRY
ORDER BY adm.DIST_TOT DESC 
LIMIT 1;

WITH airport_country AS(
	SELECT ISO_COUNTRY, ICAO
	FROM AIRPORTS
	WHERE ICAO = 'LDZA'
)
SELECT adm.ICAO_FROM, adm.ICAO_TO, adm.COUNTRY, adm.DIST_CTRY, adm.DIST_TOT  
FROM AIRPORTS a 
INNER JOIN airport_country ON airport_country.ISO_COUNTRY = a.ISO_COUNTRY 
INNER JOIN AIRPORTS_DISTANCE_MATRIX adm ON adm.ICAO_TO = a.ICAO 
WHERE adm.ICAO_FROM = airport_country.ICAO AND adm.COUNTRY = airport_country.ISO_COUNTRY
ORDER BY adm.DIST_CTRY DESC 
LIMIT 1;

SELECT * FROM AIRPORTS_DISTANCE_MATRIX
WHERE ICAO_FROM = 'LDZA' 
ORDER BY DIST_CTRY DESC 
LIMIT 1
