CREATE TABLE AERODROMI_LETOVI (
	id integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	icao varchar(10) NOT NULL,
	preuzimanje boolean NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (icao) REFERENCES airports (icao),
	CONSTRAINT AERODROMI_LETOVI_icao UNIQUE (icao)
)

GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE AERODROMI_LETOVI TO APLIKACIJA;