CREATE TABLE DNEVNIK (
	id integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	zahtjev varchar(255) NOT NULL,
	metoda varchar(10) NOT NULL,
	vrsta varchar(10) NOT NULL,
	vremenska_oznaka timestamp NOT NULL,
	PRIMARY KEY (id)
);

GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE DNEVNIK TO APLIKACIJA;

SELECT * FROM INFORMATION_SCHEMA.TABLES;

DROP TABLE DNEVNIK;