CREATE TABLE KORISNICI (
	id integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	korisnik varchar(30) NOT NULL,
	lozinka varchar(30) NOT NULL,
	ime varchar(255) NOT NULL,
	prezime varchar(255) NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT KORISNICI_korisnik UNIQUE (korisnik)
);

GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE KORISNICI TO APLIKACIJA;

DROP TABLE KORISNICI;
