SELECT CASE WHEN COUNT(*) > 0 THEN 'true' ELSE 'false' END AS REZULTAT
FROM PUBLIC.AERODROMI_LETOVI 
WHERE ICAO IN ('EBBR','EDDF','EDDM','EGGP','EGLL','EIDW','EPWA','GCLP','HEGN','LDZA','LEBL','LEPA','LFPG','EDDS','LIPZ','LOWW','LTBJ','LSZH','LJLJ','OMDB');

SELECT COUNT(*) AS count
FROM (
  SELECT DISTINCT CAST(TIMESTAMP(FIRSTSEEN) AS DATE) AS date
  FROM PUBLIC.LETOVI_POLASCI
  WHERE ESTDEPARTUREAIRPORT IN ('EBBR','EDDF','EDDM','EGGP','EGLL','EIDW','EPWA','GCLP','HEGN','LDZA','LEBL','LEPA','LFPG','EDDS','LIPZ','LOWW','LTBJ','LSZH','LJLJ','OMDB')
  GROUP BY CAST(TIMESTAMP(FIRSTSEEN) AS DATE)
  HAVING COUNT(DISTINCT ESTDEPARTUREAIRPORT) = 1
  ORDER BY date
  LIMIT 10
) AS subquery;