SELECT CASE WHEN COUNT(*) > 0 THEN 'true' ELSE 'false' END AS REZULTAT
FROM PUBLIC.AERODROMI_LETOVI 
WHERE ICAO IN ('EBBR','EDDF','EDDM','EGGP','EGLL','EIDW','EPWA','GCLP','HEGN','LDZA','LEBL','LEPA','LFPG','EDDS','LIPZ','LOWW','LTBJ','LSZH','LJLJ','OMDB');

SELECT CASE WHEN COUNT(*) >= 50000 THEN 'true' ELSE 'false' END AS REZULTAT, COUNT(*) AS UKUPNO
FROM PUBLIC.LETOVI_POLASCI;

SELECT COUNT(*) AS count
FROM (
  SELECT DISTINCT CAST(TIMESTAMP(FIRSTSEEN) AS DATE) AS date
  FROM PUBLIC.LETOVI_POLASCI
  WHERE ESTDEPARTUREAIRPORT IN ('EBBR','EDDF','EDDM','EGGP','EGLL','EIDW','EPWA','GCLP','HEGN','LDZA','LEBL','LEPA','LFPG','EDDS','LIPZ','LOWW','LTBJ','LSZH','LJLJ','OMDB')
  GROUP BY CAST(TIMESTAMP(FIRSTSEEN) AS DATE)
  HAVING COUNT(DISTINCT ESTDEPARTUREAIRPORT) = 1
  ORDER BY date
  LIMIT 10
) AS subquery;

SELECT TO_CHAR(CAST(TIMESTAMP(FIRSTSEEN) AS DATE), 'yyyy.MM.dd.')  AS DAN, COUNT(*) AS BROJ
FROM PUBLIC.LETOVI_POLASCI 
GROUP BY CAST(TIMESTAMP(FIRSTSEEN) AS DATE)
ORDER BY DAN;

SELECT ESTDEPARTUREAIRPORT, TO_CHAR(CAST(TIMESTAMP(FIRSTSEEN) AS DATE), 'dd.MM.yyyy.') AS DAN, COUNT(*) AS BROJ
FROM PUBLIC.LETOVI_POLASCI 
GROUP BY ESTDEPARTUREAIRPORT, CAST(TIMESTAMP(FIRSTSEEN) AS DATE)
ORDER BY ESTDEPARTUREAIRPORT, DAN;

SELECT ESTDEPARTUREAIRPORT, TO_CHAR(CAST(TIMESTAMP(FIRSTSEEN) AS DATE), 'dd.MM.yyyy.') AS DAN, COUNT(*) AS BROJ
FROM PUBLIC.LETOVI_POLASCI 
WHERE ESTDEPARTUREAIRPORT IN ('EBBR','EDDF','EDDM','EGGP','EGLL','EIDW','EPWA','GCLP','HEGN','LDZA','LEBL','LEPA','LFPG','EDDS','LIPZ','LOWW','LTBJ','LSZH','LJLJ','OMDB')
GROUP BY ESTDEPARTUREAIRPORT, CAST(TIMESTAMP(FIRSTSEEN) AS DATE)
ORDER BY ESTDEPARTUREAIRPORT, DAN;

SELECT ESTDEPARTUREAIRPORT, TO_CHAR(CAST(TIMESTAMP(FIRSTSEEN) AS DATE), 'dd.MM.yyyy.') AS DAN, COUNT(*) AS BROJ
FROM PUBLIC.LETOVI_POLASCI
WHERE ESTDEPARTUREAIRPORT = 'LDZA'
GROUP BY ESTDEPARTUREAIRPORT, CAST(TIMESTAMP(FIRSTSEEN) AS DATE)
ORDER BY DAN

SELECT ESTDEPARTUREAIRPORT, TO_CHAR(CAST(TIMESTAMP(FIRSTSEEN) AS DATE), 'dd.MM.yyyy.') AS DAN, COUNT(*) AS BROJ
FROM PUBLIC.LETOVI_POLASCI
WHERE TO_CHAR(CAST(TIMESTAMP(FIRSTSEEN) AS DATE), 'dd.MM.yyyy.') = '01.01.2022.'
GROUP BY ESTDEPARTUREAIRPORT, CAST(TIMESTAMP(FIRSTSEEN) AS DATE)
ORDER BY ESTDEPARTUREAIRPORT

SELECT ESTDEPARTUREAIRPORT, TO_CHAR(CAST(TIMESTAMP(FIRSTSEEN) AS DATE), 'dd.MM.yyyy.') AS DAN, COUNT(*) AS BROJ
FROM PUBLIC.LETOVI_POLASCI
WHERE TO_CHAR(CAST(TIMESTAMP(FIRSTSEEN) AS DATE), 'dd.MM.yyyy.') = '01.01.2022.'
AND ESTDEPARTUREAIRPORT IN ('EBBR','EDDF','EDDM','EGGP','EGLL','EIDW','EPWA','GCLP','HEGN','LDZA','LEBL','LEPA','LFPG','EDDS','LIPZ','LOWW','LTBJ','LSZH','LJLJ','OMDB')
GROUP BY ESTDEPARTUREAIRPORT, CAST(TIMESTAMP(FIRSTSEEN) AS DATE)
ORDER BY ESTDEPARTUREAIRPORT