{aplikacija.godina: '2023', stranica.brojRedova: '15', aplikacija.verzija: '1.00',
  autor.prezime: Kovac, autor.ime: Marijan, adresa.wa_1: 'http://200.20.0.4:8080/mkovac_zadaca_2_wa_1/api',
  autor.predmet: NWTiS}
